# Generated by Django 5.0.1 on 2024-03-28 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'Customer')], default=1),
        ),
    ]
