# Generated by Django 5.0.3 on 2024-03-29 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanManualPdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan_card_number', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=50)),
                ('upload_image', models.ImageField(upload_to='media/PanManualPdf')),
                ('upload_sign', models.ImageField(upload_to='media/PanManualPdf')),
                ('upload_file', models.FileField(upload_to='media/PanManualPdf')),
                ('status', models.IntegerField(default=0)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.customer')),
            ],
        ),
    ]
