# Generated by Django 5.0.1 on 2024-04-03 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_pmkishanregistrationnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='DLPdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dl_number', models.CharField(max_length=12)),
                ('dob', models.DateField()),
                ('mobile_number', models.CharField(max_length=12)),
                ('status', models.IntegerField(default=0)),
                ('upload_file', models.ImageField(upload_to='media/DlPdf')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.customer')),
            ],
        ),
    ]
