# Generated by Django 5.0.3 on 2024-04-03 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_findrcpdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailsToPdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=50)),
                ('select_guardian', models.CharField(max_length=50)),
                ('guardian_name', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('distric', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('pin_code', models.CharField(max_length=10)),
                ('mobile_number', models.CharField(max_length=20)),
                ('status', models.IntegerField(default=0)),
                ('upload_file', models.ImageField(upload_to='media/Detailstopdf')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.customer')),
            ],
        ),
    ]
