# Generated by Django 5.0.3 on 2024-04-06 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_detailstopdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCardPdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('distric', models.CharField(max_length=50)),
                ('block', models.CharField(max_length=50)),
                ('village', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('mobile_number', models.CharField(max_length=20)),
                ('status', models.IntegerField(default=0)),
                ('upload_file', models.ImageField(upload_to='media/Detailstopdf')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.customer')),
            ],
        ),
    ]
