# Generated by Django 5.0.3 on 2024-04-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_jobcardpdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='findpancard',
            name='is_valid',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='findpancard',
            name='prev_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
