# Generated by Django 5.0.3 on 2024-04-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_findpancard_is_valid_findpancard_prev_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailstopdf',
            name='is_valid',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='detailstopdf',
            name='prev_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='dlpdf',
            name='is_valid',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='dlpdf',
            name='prev_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='domicalcertificate',
            name='is_valid',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='domicalcertificate',
            name='prev_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='eidtouid',
            name='is_valid',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='eidtouid',
            name='prev_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='findaadharcard',
            name='is_valid',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='findaadharcard',
            name='prev_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='findayushmancardpdf',
            name='is_valid',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='findayushmancardpdf',
            name='prev_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='finddlnumber',
            name='is_valid',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='finddlnumber',
            name='prev_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='findpmkishanpaymentdetails',
            name='is_valid',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='findpmkishanpaymentdetails',
            name='prev_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='findrcpdf',
            name='is_valid',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='findrcpdf',
            name='prev_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='incomecertificate',
            name='is_valid',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='incomecertificate',
            name='prev_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='jobcardpdf',
            name='is_valid',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='jobcardpdf',
            name='prev_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='matchaadharcardtopdf',
            name='is_valid',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='matchaadharcardtopdf',
            name='prev_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='matchaadharnumber',
            name='is_valid',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='matchaadharnumber',
            name='prev_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='panmanualpdf',
            name='is_valid',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='panmanualpdf',
            name='prev_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='pmkishanregistrationnumber',
            name='is_valid',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='pmkishanregistrationnumber',
            name='prev_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='rashannumbertouid',
            name='is_valid',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='rashannumbertouid',
            name='prev_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='uidtopdf',
            name='is_valid',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='uidtopdf',
            name='prev_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
