# Generated by Django 5.0.3 on 2024-04-25 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_setkeys'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmountSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount1', models.CharField(max_length=10)),
                ('amount2', models.CharField(max_length=10)),
                ('amount3', models.CharField(max_length=10)),
                ('amount4', models.CharField(max_length=10)),
                ('amount5', models.CharField(max_length=10)),
                ('amount6', models.CharField(max_length=10)),
                ('amount7', models.CharField(max_length=10)),
                ('amount8', models.CharField(max_length=10)),
                ('amount9', models.CharField(max_length=10)),
                ('amount10', models.CharField(max_length=10)),
                ('amount11', models.CharField(max_length=10)),
                ('amount12', models.CharField(max_length=10)),
                ('amount13', models.CharField(max_length=10)),
                ('amount14', models.CharField(max_length=10)),
                ('amount15', models.CharField(max_length=10)),
                ('amount16', models.CharField(max_length=10)),
                ('amount17', models.CharField(max_length=10)),
                ('amount18', models.CharField(max_length=10)),
                ('amount19', models.CharField(max_length=10)),
                ('amount20', models.CharField(max_length=10)),
                ('amount21', models.CharField(max_length=10)),
                ('amount22', models.CharField(max_length=10)),
                ('amount23', models.CharField(max_length=10)),
                ('amount24', models.CharField(max_length=10)),
                ('amount25', models.CharField(max_length=10)),
                ('amount26', models.CharField(max_length=10)),
                ('amount27', models.CharField(max_length=10)),
                ('amount28', models.CharField(max_length=10)),
                ('amount29', models.CharField(max_length=10)),
                ('amount30', models.CharField(max_length=10)),
            ],
        ),
    ]
