# Generated by Django 5.0.3 on 2024-04-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_amountset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amountset',
            name='amount1',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='amountset',
            name='amount10',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='amountset',
            name='amount11',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='amountset',
            name='amount12',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='amountset',
            name='amount13',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='amountset',
            name='amount14',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='amountset',
            name='amount15',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='amountset',
            name='amount16',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='amountset',
            name='amount17',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='amountset',
            name='amount18',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='amountset',
            name='amount19',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='amountset',
            name='amount2',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='amountset',
            name='amount20',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='amountset',
            name='amount21',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='amountset',
            name='amount22',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='amountset',
            name='amount23',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='amountset',
            name='amount24',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='amountset',
            name='amount25',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='amountset',
            name='amount26',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='amountset',
            name='amount27',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='amountset',
            name='amount28',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='amountset',
            name='amount29',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='amountset',
            name='amount3',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='amountset',
            name='amount30',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='amountset',
            name='amount4',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='amountset',
            name='amount5',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='amountset',
            name='amount6',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='amountset',
            name='amount7',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='amountset',
            name='amount8',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='amountset',
            name='amount9',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
