# Generated by Django 5.0.3 on 2024-04-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_findpancard_order_id_findpancard_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailstopdf',
            name='order_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='detailstopdf',
            name='paid',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='detailstopdf',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='dlpdf',
            name='order_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='dlpdf',
            name='paid',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='dlpdf',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='domicalcertificate',
            name='order_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='domicalcertificate',
            name='paid',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='domicalcertificate',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='eidtouid',
            name='order_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='eidtouid',
            name='paid',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='eidtouid',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='findaadharcard',
            name='order_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='findaadharcard',
            name='paid',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='findaadharcard',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='findayushmancardpdf',
            name='order_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='findayushmancardpdf',
            name='paid',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='findayushmancardpdf',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='finddlnumber',
            name='order_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='finddlnumber',
            name='paid',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='finddlnumber',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='findpmkishanpaymentdetails',
            name='order_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='findpmkishanpaymentdetails',
            name='paid',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='findpmkishanpaymentdetails',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='findrcpdf',
            name='order_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='findrcpdf',
            name='paid',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='findrcpdf',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='incomecertificate',
            name='order_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='incomecertificate',
            name='paid',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='incomecertificate',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='jobcardpdf',
            name='order_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='jobcardpdf',
            name='paid',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='jobcardpdf',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='matchaadharcardtopdf',
            name='order_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='matchaadharcardtopdf',
            name='paid',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='matchaadharcardtopdf',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='matchaadharnumber',
            name='order_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='matchaadharnumber',
            name='paid',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='matchaadharnumber',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='panmanualpdf',
            name='order_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='panmanualpdf',
            name='paid',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='panmanualpdf',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pmkishanregistrationnumber',
            name='order_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pmkishanregistrationnumber',
            name='paid',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='pmkishanregistrationnumber',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='rashannumbertouid',
            name='order_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='rashannumbertouid',
            name='paid',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='rashannumbertouid',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='uidtopdf',
            name='order_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='uidtopdf',
            name='paid',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='uidtopdf',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
